### ISSUE TITLE
Gumshoe IE 11/Edge issues - undefined

### ISSUE THREAD

**Issue by Amckenzie93** [gilt-labs/Gumshoe#2]
Hello fellow Devs,

I have been implementing Gumshoe onto a project at work and found that its functioning across all browsers bar IE (surprise surprise!) and im wondering what im doing wrong, had a look through the documentation and can see that it is supported, however when i run the script at the end of my document to Initialize gumshoe, it flops with 'gumshoe' is undefined, even though the script is loaded on the page (tried it in the head and footer etc) and i can see this in my network tab with a 200 response (also again, its working on other browsers, fully functional as expected).

Im running this on Internet Explorer 11/Edge, and simply making the call to gumshoe.init() at the end of my page when the document is ready.. any thoughts on the issue?

Thanks in advance!

**Comment by shellscape** [comment]
any chance you're in a different scope than gumshoe was loaded in?

I'd inspect the `window` object to see if gumshoe is attached to that prior to calling `gumshoe.init`.

And as an alternative, you can feed Gumshoe a Promise. Here's how we init gumshoe. See the inline comment I left there for you:

```js
  /**
   * Initializes this module.
   *
   * @public
   * @method init
   */
  function init (opts) {

    options = _.extend(options, opts || {});

    var setup = function setup () {

      if (!window.gumshoe) {
        exception('Gumshoe: window.gumshoe is undefined. setup() cannot continue and Gumshoe will not send events.');
        return;
      }

      // The script is added to the page in dom.chassis/templates/bottom.handlebars
      log.info('Using Gumshoe v' + window.gumshoe.version);

      transport.init(options);

      // tell gumshoe to use our transport
      window.gumshoe({ transport: 'gilt-svc-event' });

      // send the pageView event - all pages will send this event.
      send('page.view');
    };

    // @Amckenzie93 - if gumshoe exists on window, move ahead.
    // otherwise, use a Promise (we're using when.js) and setup after
    // gumshoe has signaled it's ready. Gumshoe recognizes the promise
    // if one is setup. this helps avoid race conditions.
    if (window.gumshoe) {
      setup();
    }
    else {
      window.gumshoe = { ready: when.defer() };

      when
        .all(window.gumshoe.ready)
        .then(setup);
    }
  }
```
